nodes:
- type: device
  points:
  - type: description
    text: siot
  children:
  - type: user
    points:
    - type: email
      text: admin
    - type: firstName
      text: admin
    - type: lastName
      text: user
    - type: pass
      text: admin
  - type: metrics
    points:
    - type: description
      text: Metrics System
    - type: type
      text: system
    - type: period
      value: 60
  - type: db
    points:
    - type: description
      text: Victoria Metrics
    - type: uri
      text: http://localhost:8428
    - type: tagPointType
      text: tag
  - type: metrics
    points:
    - type: description
      text: Metrics SIOT
    - type: type
      text: app
    - type: period
      value: 60
  - type: metrics
    points:
    - type: description
      text: Metrics grafana
    - type: type
      text: process
    - type: name
      text: grafana
    - type: period
      value: 60
  - type: metrics
    points:
    - type: description
      text: Metrics Victoria Metrics
    - type: type
      text: process
    - type: name
      text: victoria-metrics-prod
    - type: period
      value: 60
