#!/usr/bin/env python3
"""Turn a `siot export` dump into an importable Simple IoT configuration.

An export captures one running instance: generated IDs, an origin on every
operator-set point, and whatever the clients have collected so far. An
import file wants none of that. It wants the configuration only, so the
same file installs on any number of devices.

This reads an export on stdin, or from a path, and writes a configuration
on stdout:

  siot export | ./sanitize-siot-export.py \\
      > recipes-iot/siot-config/files/siot-config.yml

Reference: https://docs.simpleiot.org/docs/user/configuration.html
"""

import argparse
import sys

import yaml

# Node types kept by default: the whole tree an instance is built from,
# suitable for importing at the root of a fresh store. Narrow this with
# --keep when the target already provides some of it. Dropping 'device'
# and 'user', for instance, leaves the nodes that attach beneath a device
# node that already exists.
DEFAULT_KEEP = ("device", "user", "metrics", "db", "gps")

# Written above every generated file, so the next person to open one knows
# where it came from and what it leaves out. A layer with more to say adds
# its own lines with --header.
DEFAULT_HEADER = """\
Generated by sanitize-siot-export.py from a `siot export` capture.

Node IDs are left out on purpose: Simple IoT assigns a new one to every node
it imports, so this file serves any number of devices. Collected points are
left out as well, since the clients fill those in as they run.

Regenerate rather than editing by hand whenever the change is easier to make
in the portal:

  siot export | sanitize-siot-export.py [--header FILE] > this-file.yml

Reference: https://docs.simpleiot.org/docs/user/configuration.html\
"""

# Points an operator sets, per node type, in the order they read best.
# Every other point on these nodes is collected data.
CONFIG_POINTS = {
    "device": ("description",),
    "user": ("email", "firstName", "lastName", "pass", "phone"),
    "metrics": ("description", "type", "name", "period"),
    "db": ("description", "uri", "tagPointType"),
    # A gps node also carries the fix it is reporting, along with rxReset
    # and errorCountReset, which are momentary commands an operator sends
    # to clear a counter instead of settings worth shipping.
    "gps": ("description", "disabled", "gpsSource", "port", "baud",
            "gpsdAddress", "debug"),
}


def config_points(node):
    """Return the node's configuration points, ordered, data dropped."""
    order = CONFIG_POINTS.get(node["type"])
    points = node.get("points") or []

    if order is None:
        # An unrecognized type keeps everything. Better to hand the
        # reviewer too much than to drop a setting silently.
        print(
            f"note: keeping all points on unrecognized node type "
            f"'{node['type']}', review them by hand",
            file=sys.stderr,
        )
        return [strip_point(p) for p in points]

    kept = []
    for want in order:
        for point in points:
            # An export writes a point for every field a client knows
            # about, including the ones nobody filled in. Those carry no
            # setting, so they are left out.
            if point["type"] == want and ("text" in point or "value" in point):
                kept.append(strip_point(point))
    return kept


def strip_point(point):
    """Drop per-point export bookkeeping and tidy whole-number values."""
    out = {k: v for k, v in point.items() if k != "origin"}
    # Export writes every value as a float. Whole numbers read better as
    # integers, and Simple IoT parses either into the same float64.
    if isinstance(out.get("value"), float) and out["value"].is_integer():
        out["value"] = int(out["value"])
    return out


def sanitize_nodes(nodes, keep):
    """Filter a node tree down to the configuration worth shipping.

    A node whose type is not kept still gives up its children, which move
    into its place. That is what turns an export rooted at a device node
    into a flat list ready to import beneath a device node that already
    exists on the target.
    """
    out = []
    for node in nodes or []:
        children = sanitize_nodes(node.get("children"), keep)
        if node["type"] not in keep:
            out.extend(children)
            continue
        # 'id' and 'parent' name this instance's nodes. Leaving them out
        # lets Simple IoT generate fresh ones on every device.
        entry = {"type": node["type"], "points": config_points(node)}
        if children:
            entry["children"] = children
        out.append(entry)
    return out


def write_comment(text, out):
    """Write a block of prose as YAML comments."""
    for line in text.rstrip("\n").split("\n"):
        out.write(f"# {line}\n" if line.strip() else "#\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "export",
        nargs="?",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="export file to read (default: stdin)",
    )
    parser.add_argument(
        "--keep",
        default=",".join(DEFAULT_KEEP),
        help=(
            "comma-separated node types to keep; the children of a type "
            f"left out move up in its place (default: {','.join(DEFAULT_KEEP)})"
        ),
    )
    parser.add_argument(
        "--header",
        type=argparse.FileType("r"),
        help=(
            "file of prose to write as comments above the default header, "
            "for whatever a layer needs to say about its own configuration"
        ),
    )
    parser.add_argument(
        "--no-header",
        action="store_true",
        help="write the configuration alone, with no leading comments",
    )
    args = parser.parse_args()

    doc = yaml.safe_load(args.export)
    nodes = sanitize_nodes(doc.get("nodes"), keep=set(args.keep.split(",")))

    if not nodes:
        print("note: no nodes matched --keep, output is empty", file=sys.stderr)

    # Comments go in ahead of the dump, since PyYAML drops the ones an
    # export carried and cannot write new ones itself.
    if not args.no_header:
        if args.header:
            write_comment(args.header.read(), sys.stdout)
            sys.stdout.write("#\n")
        write_comment(DEFAULT_HEADER, sys.stdout)
        sys.stdout.write("\n")

    yaml.safe_dump({"nodes": nodes}, sys.stdout, sort_keys=False, default_flow_style=False)


if __name__ == "__main__":
    main()
